name: Generate GitHub Profile 3D Contributions

on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "12 1 * * *"
    - cron: "24 2 * * *"
    - cron: "36 3 * * *"
    - cron: "48 4 * * *"
    - cron: "0 6 * * *"
    - cron: "12 7 * * *"
    - cron: "24 8 * * *"
    - cron: "36 9 * * *"
    - cron: "48 10 * * *"
    - cron: "0 12 * * *"
    - cron: "12 13 * * *"
    - cron: "24 14 * * *"
    - cron: "36 15 * * *"
    - cron: "48 16 * * *"
    - cron: "0 18 * * *"
    - cron: "12 19 * * *"
    - cron: "24 20 * * *"
    - cron: "36 21 * * *"
    - cron: "48 22 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate 3D Contributions
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push Changes
        run: |
          git config user.name kangeunchan
          git config user.email kangeunchan080310@gmail.com
          git remote set-url origin https://github.com/kangeunchan/kangeunchan.git
          git add -A
          git commit -m "generate: 3D contributions for GitHub profile"
          git push https://$GITHUB_TOKEN@github.com/kangeunchan/kangeunchan.git
